export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const LOAD_USER_READINGS = 'LOAD_USER_READINGS';
export const REMOVE_USER_READING = 'REMOVE_USER_READING';